library("caret")
library("irlba")
library("pbapply")
library("MLmetrics")
library("magrittr")
library("tidyverse")

source("classes.R")
source("eigenDecompose.R")
source("getFeatureSpace.R")
source("methods.R")
source("performance_utils.R")
source("projectNewData.R")
source("scPredict.R")
source("scPredSeurat.R")
source("training_utils.R")
source("trainModel.R")
source("utils.R")

for (i in 1:10){
 filename <- paste0("group_", i)
 trainFile_X <- paste0(filename, "_train_X")
 trainFile_Y <- paste0(filename, "_train_Y_ml")
 testFile <- paste0(filename, "_test_X")
 
 train_data <- read.csv(trainFile_X, header = T)
 test_data <- read.csv(testFile, header = T)
 train_info <- read.csv(trainFile_Y, header = T)
 train_data <- as.matrix(train_data)
 test_data <- as.matrix(test_data)
 train_data <- t(train_data)
 test_data <- t(test_data)
 
 set.seed(1234)
 scp <- eigenDecompose(train_data, n = 10)
 scp@metadata <- train_info
 scp <- getFeatureSpace(scp, pVar = "celltype")
 scp <- trainModel(scp, seed = 66)
 scp <- scPredict(scp, newData = test_data, threshold = 0.0)
 res <- getPredictions(scp)
 res <- as.data.frame(res)
 resultFile <- paste0("scPred_result_group_", i, ".csv")
 write.csv(res, resultFile, row.names = F, quote = F)
}
